version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  strapi:
    build: ./strapi-cms
    ports:
      - "1337:1337"
    volumes:
      - ./strapi-cms:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    depends_on:
      - postgres

  nextjs:
    build: ./next-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./next-frontend:/app
      - /app/node_modules
    depends_on:
      - strapi
      - favorites-service

  favorites-service:
    build: ./nest-favorites-service
    ports:
      - "3001:3001"
    volumes:
      - ./nest-favorites-service:/app
      - /app/node_modules
